In [23]:
import numpy as np

checking benifits of numpy 

In [24]:
import sys

list = range(1000)    #python list
print(sys.getsizeof(0)*len(list))  # print memory used in python list

array = np.arange(1000)
print(array.size*array.itemsize)   #print memory used in numpy array

24000
8000


In [25]:
import time

size=10000000

list1 = range(size)
list2 = range(size)

array1 = np.arange(size)
array2 = np.arange(size)

#analysing  pyhton list operation 
startTime = time.time()
result = [(x+y) for x,y in zip(list,list2)]
print("Time took from python list:\t",(time.time()-startTime)*1000)

#analysing  pyhton list operation 
startTime2 = time.time()
result1 = array1 + array2
print("Time took from numpy array:\t",(time.time()-startTime2)*1000)

Time took from python list:	 0.16808509826660156
Time took from numpy array:	 27.894020080566406


From geekforgeeks

In [26]:
# importing required packages
import numpy
import time


# size of arrays and lists
size = 1000000

# declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# Concatenation
print("\nConcatenation:")

# list
initialTime = time.time()
list1 = list1 + list2

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.concatenate((array1, array2),
						axis = 0)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Dot Product
dot = 0
print("\nDot Product:")

# list
initialTime = time.time()
for a, b in zip(list1, list2):
		dot = dot + (a * b)
		
# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.dot(array1, array2)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Scalar Addition
print("\nScalar Addition:")

# list
initialTime = time.time()
list1 =[i + 2 for i in range(size)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array1 = array1 + 2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Deletion
print("\nDeletion: ")

# list
initialTime = time.time()
del(list1)

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
del(array1)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")



Concatenation:
Time taken by Lists : 0.017345666885375977 seconds
Time taken by NumPy Arrays : 0.0032019615173339844 seconds

Dot Product:
Time taken by Lists : 0.1394670009613037 seconds
Time taken by NumPy Arrays : 0.0012640953063964844 seconds

Scalar Addition:
Time taken by Lists : 0.052323102951049805 seconds
Time taken by NumPy Arrays : 0.0013921260833740234 seconds

Deletion: 
Time taken by Lists : 0.009880781173706055 seconds
Time taken by NumPy Arrays : 4.7206878662109375e-05 seconds


Checking convienence of usage

In [28]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print("a1 + a2 is :\t", a1 + a2)
print("a1 - a2 is :\t", a1 - a2)
print("a1 * a2 is :\t", a1 * a2)
print("a1 / a2 is :\t", a1 / a2)



a1 + a2 is :	 [5 7 9]
a1 - a2 is :	 [-3 -3 -3]
a1 * a2 is :	 [ 4 10 18]
a1 / a2 is :	 [0.25 0.4  0.5 ]


Basic operations

In [51]:
elementsArray=[1,2,3,4,5]
print("Accesing array elements:\t",elementsArray[2])

#creating multidimentional array
a = np.array([[1,2],[3,4]])
print("Print array:\n",a)
print("Dimension of the array:\t", a.ndim)
print("Shape of the array:\t", a.shape)

print("Item size:\t",a.itemsize)
print("DataType:\t",a.dtype)

#crating array of different data type
a_ = np.array([[1,2],[3,4]], dtype=np.float64)
print("Print array:\n",a_)
print("Item size:\t",a_.itemsize)
print("DataType:\t",a_.dtype)

print("Sige of an array:\t",a.size)
a1_ = np.array([[1,2],[3,4]], dtype=complex)
print("Print array:\n",a1_)


Accesing array elements:	 3
Print array:
 [[1 2]
 [3 4]]
Dimension of the array:	 2
Shape of the array:	 (2, 2)
Item size:	 8
DataType:	 int64
Print array:
 [[1. 2.]
 [3. 4.]]
Item size:	 8
DataType:	 float64
Sige of an array:	 4
Print array:
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [56]:
#creating matix of zeros
zmatrix=np.zeros((3,2), dtype=int)    #3 row 2 col 
print("zero matrix:\n",zmatrix)

omatrix=np.ones((3,2))    #3 row 2 col 
print("ones matrix:\n",omatrix)

zero matrix:
 [[0 0]
 [0 0]
 [0 0]]
ones matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [76]:
#creating array range
list= range(10)   # 0-9
print("Elements in array", list[3])

#numpy array
array = np.arange(10)   # 0-9
print("Elements in numpy array", array)
array = np.arange(0,5)   # 0-4
print("Elements in numpy array", array)
array = np.arange(0,10,2)   # 0-4 with step of 2 number
print("Elements in numpy array", array)
array = np.linspace(0,5,10)   # generate 10 numbers between 0 to 5
print("Elements in numpy array", array)


Elements in array 3
Elements in numpy array [0 1 2 3 4 5 6 7 8 9]
Elements in numpy array [0 1 2 3 4]
Elements in numpy array [0 2 4 6 8]
Elements in numpy array [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [89]:
#reshape a matrix !codition: match the elements
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)
a.reshape(6,1)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
